#!/bin/sh

# Run tests
echo "./gradlew test"
./gradlew test
if [ $? -ne 0 ] ; then
  echo "\n\n\033[1;31mFailed tests. Please fix before committing.\033[0m\n\n"
  exit $?
fi

# Run lint
echo "./gradlew lintKotlin"
./gradlew lintKotlin
if [ $? -ne 0 ] ; then
  echo
  echo "\n\n\033[1;31mFailed kotlin lint check. You may run './gradlew formatKotlin' to automatically format kotlin,\nor check above output for individual errors.\033[0m\n\n"
  exit $?
fi

exit 0
