#!/bin/sh

# Run lint
echo "./gradlew formatKotlin"
./gradlew formatKotlin
if [ $? -ne 0 ] ; then
  echo
  echo "\n\n\033[1;31mFailed kotlin format. Please check above for errors. \033[0m\n\n"
  exit 1
fi

# Run tests
echo "./gradlew test"
./gradlew test
if [ $? -ne 0 ] ; then
  echo "\n\n\033[1;31mFailed tests. Please fix before committing.\033[0m\n\n"
  exit 1
fi

exit 0
